mariadb:
  enabled: false
  hostname: localhost:3306
  username: name
  password: pass
  database: db

greylist:
  group: trusted
  track: greylist

# Point the IP to webserver
listener:
  ip: localhost
  port: 20000

arcanelog:
  ip: localhost
  port: 25555

spy:
  # Seconds to wait before broadcasting since last mined block
  xray-wait-duration: 5
