mariadb:
  enabled: false
  hostname: localhost:3306
  username: name
  password: pass
  database: db

greylist:
  group: trusted
  track: greylist

# Point the IP to webserver
web-listener:
  ip: localhost
  port: 20000

discord:
  token: 0
  guild-id: 0
  player-role-id: 0
  mc-chat:
    channel-id: 0
    webhook-url: https://discordapp.com/api/webhooks/[id]/[token]

# Point to the ArcaneLog plugin's ServerSocket
arcanelog:
  ip: localhost
  port: 25555

spy:
  # Seconds to wait before broadcasting since last mined block
  xray-wait-duration: 5
