name: ArcaneBungee
version: ${project.version}
author: Arcane Survival
description: Local chat, private messaging, and badge, written for Arcane Survival.
main: com.arcaneminecraft.bungee.ArcaneBungee
