name: ArcaneChatUtils
version: 2.0.0-SNAPSHOT
authors: [Mark Talrey, SimonOrJ]
description: Local chat and AFK functions, written for Arcane Survival.
main: com.arcaneminecraft.chatutils.ArcaneChatUtils
website: https://arcaneminecraft.com/

depend: [ArcaneSurvival]

commands:
  a:
    description: Staff Chat Channel
    permission: arcane.staffchat
  atoggle:
    aliases: [at]
    description: Toggle Staff Chat
    permission: arcane.staffchat
  local:
    aliases: [l]
    description: Sends a chat message to all players within range.
    usage: /local -h for detailed help.
  localtoggle:
    aliases: [ltoggle, lt]
    description: Toggles your chat state to local only.
    usage: /localtoggle -h for detailed help.
  localradius:
    aliases: [lradius, lr]
    descriptioni: Sets a new radius
    usage: /localradius <radius>
  global:
    aliases: [g]
    description: Sends a chat message to the whole server, regardless of ltoggle state.
    usage: /global <message>
  tell:
    aliases: [t, message, msg, m]
    description: Private Message someone
    usage: /tell <player> <message>
  reply:
    aliases: [r]
    description: Reply to the person who sent you last message
    usage: /reply <message>

permissions:
  arcane.staffchat:
    description: Send and receive messages from Staff Chat channel
    default: op
  acu.murder:
    description: this player can /kill others.
    default: op
