name: ArcaneChatUtils
version: ${project.version}
authors: [Mark Talrey, SimonOrJ]
description: Local chat, private messaging, and badge, written for Arcane Survival.
main: com.arcaneminecraft.chatutils.ArcaneChatUtils
