name: ArcaneChatUtils
version: 4.0.0-SNAPSHOT
authors: [Mark Talrey, SimonOrJ]
description: Local chat and AFK functions, written for Arcane Survival.
main: com.arcaneminecraft.chatutils.ArcaneChatUtils
website: https://arcaneminecraft.com/

depend: [ArcaneSurvival]

commands:
  local:
    aliases: [l]
    description: Sends a chat message to all players within range.
    usage: /local -h for detailed help.
  ltoggle:
    description: Toggles your chat state to local only.
    usage: /ltoggle -h for detailed help.
  global:
    aliases: [g]
    description: Sends a chat message to the whole server, regardless of ltoggle state.
    usage: /global <message>
  tell:
    aliases: [t, message, msg, m]
    description: Private Message someone
    usage: /tell <player> <message>
  reply:
    aliases: [r]
    description: Reply to the person who sent you last message
    usage: /reply <message>

permissions:
  acu.murder:
    description: this player can /kill others.
    default: op
